// ─── Aves del Odiel: datos y sprites pixel art (16×16) ───────────────────────
// Cada sprite se dibuja como una matriz de caracteres; el parser del motor
// convierte cada carácter en un píxel usando la paleta `pal` de la especie.
// Textos basados en la Guía de Aves de la ría de Huelva (Autoridad Portuaria).

export interface Sprite {
  pal: Record<string, string>;
  px: string[];
}

export type Phase = "dawn" | "day" | "dusk" | "night";
export type Zone = "carrizal" | "fangal" | "matorral" | "agua";
export type Rarity = 0 | 1 | 2 | 3;

export interface Bird {
  id: string;
  name: string;
  sci: string;
  family: string;
  rarity: Rarity;
  size: string;
  wingspan: string;
  desc: string;
  fact?: string;
  zones: Zone[];
  time: Record<Phase, number>;
  skittish: number; // 1 tranquila … 5 muy asustadiza (dificulta la foto)
  cry: 0 | 1 | 2 | 3; // tipo de canto
  sprite: Sprite;
}

export const RARITY_LABEL = ["Común", "Poco común", "Rara", "Mítica"];
export const RARITY_COLOR = ["#93d48c", "#56c9bd", "#ffb43a", "#ff6f5e"];
export const SIGHT_POINTS = [40, 80, 160, 320];
export const PHOTO_BONUS = [0, 60, 140, 260];
export const PHOTO_LABEL = ["—", "Borrosa", "Buena", "Perfecta"];

const K = "#241830"; // contorno universal

const allDay = { dawn: 1, day: 1, dusk: 1, night: 1 };

export const BIRDS: Bird[] = [
  {
    id: "flamenco",
    name: "Flamenco común",
    sci: "Phoenicopterus roseus",
    family: "Phoenicopteridae",
    rarity: 1,
    size: "110–150 cm",
    wingspan: "140–170 cm",
    desc: "Filtra agua y fango con su pico curvado, con la cabeza boca abajo, para atrapar artemias y algas: de ahí viene su rosa inconfundible. En las salinas del Odiel forma bandos que tiñen la marisma.",
    fact: "La guía lo pone como ejemplo de identificación por hábitat: «los flamencos no aparecen en las montañas». Su mundo es el agua somera.",
    zones: ["agua", "fangal"],
    time: { dawn: 1.2, day: 1, dusk: 1.4, night: 0.4 },
    skittish: 3,
    cry: 1,
    sprite: {
      pal: { k: K, p: "#ff9fb6", P: "#e76f92", B: "#241830", Y: "#f4d9c0" },
      px: [
        "................",
        "....kkkk........",
        "...kppppk.......",
        "..kBppppk.......",
        "..kYkBppk.......",
        "..kkk.kpk.......",
        "......kpk.......",
        "......kppk......",
        ".....kppppk.....",
        "...kkppppppkk...",
        "..kppppppppppk..",
        "..kpPpppppppPpk.",
        "...kppppppppk...",
        "....kppppppk....",
        ".....kpk.kpk....",
        ".....kkk.kkk....",
      ],
    },
  },
  {
    id: "espatula",
    name: "Espátula común",
    sci: "Platalea leucorodia",
    family: "Threskiornithidae",
    rarity: 1,
    size: "80–93 cm",
    wingspan: "120–135 cm",
    desc: "Barre el agua somera con su pico en forma de cuchara, de lado a lado, cazando camarones y pececillos. Es el símbolo del Odiel: su silueta blanca preside las salinas.",
    fact: "La guía del puerto la cita entre las especies amenazadas que se reproducen en el paraje, junto al águila pescadora.",
    zones: ["fangal", "agua"],
    time: { dawn: 1.3, day: 1, dusk: 1.3, night: 0.2 },
    skittish: 3,
    cry: 1,
    sprite: {
      pal: { k: K, w: "#f7f3e8", s: "#d8d4c8", b: "#241830", y: "#f0c060" },
      px: [
        "................",
        "....kkkk........",
        "...kwwwwk.......",
        "...kwkwwk.......",
        "..kkbwwwwk......",
        ".kbbbbkwwwk.....",
        ".kbbbbykwwk.....",
        ".kkkkykkkk......",
        "......kwwwkk....",
        ".....kwwwwwwk...",
        "....kwwwwwwwsk..",
        "....kwwwwwwwsk..",
        ".....kwwwwwk....",
        "......kwwk......",
        "......kk.kk.....",
        ".....kk...kk....",
      ],
    },
  },
  {
    id: "garza-real",
    name: "Garza real",
    sci: "Ardea cinerea",
    family: "Ardeidae",
    rarity: 0,
    size: "90–100 cm",
    wingspan: "150–175 cm",
    desc: "Caza inmóvil como una estatua gris y arponea peces con su pico a velocidad de vértigo. Es la garza europea más grande y la más fácil de ver en los caños.",
    fact: "Su envergadura roza los 175 cm. En vuelo pliega el cuello en uve: su silueta sobre la ría es inconfundible.",
    zones: ["agua", "fangal"],
    time: allDay,
    skittish: 2,
    cry: 1,
    sprite: {
      pal: { k: K, G: "#9fb3c4", w: "#f7f3e8", n: "#2a3140", y: "#e8b64c", L: "#5c6b7d" },
      px: [
        "................",
        "....kkkk........",
        "...kwwnnk.......",
        "...kykwGk.......",
        "...kykkGk.......",
        "....kk.kGk......",
        ".......kGk......",
        ".......kwk......",
        "......kwwk......",
        ".....kwwwkk.....",
        "...kwwGGGGkk....",
        "..kGGGGGGGGGk...",
        "..kGGGGGGGGGk...",
        "...kGGGGGGGk....",
        "....kLG.kLGk....",
        "...kkkk.kkkk....",
      ],
    },
  },
  {
    id: "garceta",
    name: "Garceta común",
    sci: "Egretta garzetta",
    family: "Ardeidae",
    rarity: 0,
    size: "55–65 cm",
    wingspan: "88–106 cm",
    desc: "Pequeña garza blanca de patas negras que agita una pata bajo el agua para asustar a los peces escondidos en el fango. Imposible confundirla: parece un copo de nieve con zancos.",
    fact: "En plumaje nupcial luce dos largas plumas ornamentales en el dorso: las famosas «aigrettes» que casi la llevan a la extinción por culpa de la moda.",
    zones: ["fangal", "agua"],
    time: { dawn: 1.2, day: 1, dusk: 1, night: 0.2 },
    skittish: 2,
    cry: 1,
    sprite: {
      pal: { k: K, w: "#f7f3e8", s: "#d8d4c8", y: "#e8b64c" },
      px: [
        "................",
        ".....kkkk.......",
        "...k.kwwk.......",
        "...kkkwwwk......",
        "...kykwwwk......",
        "....kkkwwk......",
        "......kwwk......",
        "......kwwwk.....",
        ".....kwwwwkk....",
        "....kwwwwwwwk...",
        "...kwwwwwwssk...",
        "....kwwwwwssk...",
        ".....kwwwwwk....",
        "......kwwwk.....",
        "......kk.kk.....",
        "......k...k.....",
      ],
    },
  },
  {
    id: "ciguena-blanca",
    name: "Cigüeña blanca",
    sci: "Ciconia ciconia",
    family: "Ciconiidae",
    rarity: 0,
    size: "100–115 cm",
    wingspan: "195–215 cm",
    desc: "Planea sobre la ría con las alas en cruz, blanca y negra, con el pico y las patas rojos. Cruza el estrecho de Gibraltar rumbo a África, aunque cada vez se queda más tiempo todo el año.",
    fact: "Apenas tiene voz: se comunica crotoreando, chocando el pico como unas castañuelas que se oyen en todo el paraje.",
    zones: ["carrizal", "agua"],
    time: { dawn: 1.2, day: 1.2, dusk: 1, night: 0.1 },
    skittish: 2,
    cry: 1,
    sprite: {
      pal: { k: K, w: "#f7f3e8", n: "#23242e", r: "#e04038" },
      px: [
        "................",
        "....kkkk........",
        "...kwwwwk.......",
        "...kwkwwk.......",
        "...kkwwwwk......",
        "....kkwwwwrrkk..",
        "......kwwwwwrk..",
        "......kwwwkkk...",
        ".....kwwwwwwk...",
        "...kkwwwwwwwk...",
        "..kwwwwwwnnnk...",
        "..kwwwwwwnnnnk..",
        "..kwwwwwnnnnnk..",
        "...kwwwwnnnnk...",
        "....krrk.krrk...",
        "....krk...krk...",
      ],
    },
  },
  {
    id: "gallineta",
    name: "Gallineta común",
    sci: "Gallinula chloropus",
    family: "Rallidae",
    rarity: 0,
    size: "32–35 cm",
    wingspan: "50–62 cm",
    desc: "Nada a impulsos rítmicos picoteando entre la vegetación de las orillas, como una gallina. La punta amarilla del pico contrasta con su escudete frontal rojo.",
    fact: "Cuando se alarma, sacude la cola arriba y abajo mostrando el blanco de debajo: es la señal de alarma de la marisma.",
    zones: ["carrizal", "agua"],
    time: { dawn: 1.3, day: 1, dusk: 1.3, night: 0.4 },
    skittish: 3,
    cry: 1,
    sprite: {
      pal: { k: K, n: "#3a3f4a", r: "#e04038", y: "#e8c84c", w: "#f7f3e8", g: "#5b7f3b" },
      px: [
        "................",
        "......nnnn......",
        ".....knnnnk.....",
        ".....krknnnk....",
        ".....kykknnk....",
        "......knnnnk....",
        "......knnnnk....",
        ".....knnnnnnk...",
        "....knnnnnnnnk..",
        "...knnnnnnnnnnk.",
        "...kwwwwwwwwnnk.",
        "....knnnnnnnnk..",
        ".....knnnnnnk...",
        ".....knnnnnnk...",
        ".....k.gk.gk....",
        ".....gg.gg.gg...",
      ],
    },
  },
  {
    id: "zarapito",
    name: "Zarapito real",
    sci: "Numenius arquata",
    family: "Scolopacidae",
    rarity: 1,
    size: "50–60 cm",
    wingspan: "89–106 cm",
    desc: "Su larguísimo pico curvado hacia abajo esquiva las matas de espartina para buscar crustáceos con la marea baja. Al posarse oscila la cola en un vaivén inconfundible.",
    fact: "La guía recuerda que en Huelva se marcó un zarapito que luego fue visto en Mauritania: más de 2.000 km de viaje sobre el mar.",
    zones: ["fangal"],
    time: { dawn: 1.3, day: 1, dusk: 1.2, night: 0.1 },
    skittish: 4,
    cry: 0,
    sprite: {
      pal: { k: K, b: "#8a6a44", s: "#c8a878", w: "#f2ead4", n: "#3a3028", g: "#7d8b6b" },
      px: [
        "................",
        "....bbbb........",
        "...kbbbbk.......",
        "...kbkbbk.......",
        "...kkkbbbkkkk...",
        ".......kbbbbbkkk",
        ".......kbbbbbnnk",
        ".......kbbbbnnk.",
        "......kbsbbbbbkk",
        ".....kbsbbbbbbk.",
        "....kbsbbbbbbbk.",
        "....kwwbbbbbbsk.",
        ".....kwwbbbbbk..",
        "......kwwwwbk...",
        ".....kgk...kgk..",
        ".....kgk...kgk..",
      ],
    },
  },
  {
    id: "chorlitejo",
    name: "Chorlitejo patinegro",
    sci: "Charadrius alexandrinus",
    family: "Charadriidae",
    rarity: 0,
    size: "15–17 cm",
    wingspan: "42–48 cm",
    desc: "Corre por la orilla con paradas bruscas, picoteando el fango. Su nido es apenas un hueco en la arena: un camuflaje perfecto salpicado de conchas.",
    zones: ["fangal"],
    time: { dawn: 1.2, day: 1.3, dusk: 1, night: 0.05 },
    skittish: 4,
    cry: 0,
    sprite: {
      pal: { k: K, b: "#b8a888", w: "#f7f3e8", n: "#241830", y: "#e8b64c" },
      px: [
        "................",
        "................",
        ".....bbbbk......",
        "....kbbbbbk.....",
        "....ykbkbbbk....",
        "....ykkbbbbk....",
        ".....kwwbbbk....",
        ".....kwwbbbkk...",
        "....kwwwbbnnnk..",
        "....kwwwbbbnnk..",
        "....kwwwwbbbk...",
        ".....kwwwwbk....",
        "......kwwk......",
        "......knnk......",
        ".....nk..nk.....",
        ".....nn..nn.....",
      ],
    },
  },
  {
    id: "avoceta",
    name: "Avoceta común",
    sci: "Recurvirostra avosetta",
    family: "Recurvirostridae",
    rarity: 1,
    size: "42–45 cm",
    wingspan: "77–80 cm",
    desc: "Blanca y negra, con el pico curvado hacia arriba: nada como la espátula, barriendo el agua de lado a lado. Patas largas azuladas para vadear sin mojarse el plumaje.",
    zones: ["fangal", "agua"],
    time: { dawn: 1.2, day: 1, dusk: 1.2, night: 0.1 },
    skittish: 4,
    cry: 0,
    sprite: {
      pal: { k: K, w: "#f7f3e8", n: "#241830", l: "#9fb3c4" },
      px: [
        "................",
        "................",
        "...nn...........",
        "..kkwk..........",
        "..kwwwkkkk......",
        "..kwwkwwwwkk....",
        "...kkwwwwwwwk...",
        ".....kwwwwwwk...",
        "....kwwwwwwwk...",
        "...kwwwnnnnnnk..",
        "..kwwwwnnnnnnk..",
        "..kwwwwnnnnnk...",
        "...kwwwwwwwwk...",
        "....kwwwwwwk....",
        "....klk..klk....",
        "....klk..klk....",
      ],
    },
  },
  {
    id: "gaviota-reidora",
    name: "Gaviota reidora",
    sci: "Chroicocephalus ridibundus",
    family: "Laridae",
    rarity: 0,
    size: "37–43 cm",
    wingspan: "94–110 cm",
    desc: "En plumaje nupcial luce la cabeza casi negra, con la nuca y el cuello blancos; en invierno solo conserva una mancha tras el ojo. Come casi de cualquier resto.",
    fact: "Su nombre viene de su voz: un «kiarr-kiarr» escandaloso que se oye en toda la ría cuando el bando se altera.",
    zones: ["agua"],
    time: allDay,
    skittish: 2,
    cry: 1,
    sprite: {
      pal: { k: K, w: "#f7f3e8", n: "#4a3038", g: "#9fb0bd", r: "#e04038" },
      px: [
        "................",
        ".....nnnnk......",
        "....knnnnnk.....",
        "....krknnnk.....",
        "....kkknnwk.....",
        "......kwwwk.....",
        ".....kwwwwwk....",
        "....kwwwwwwwk...",
        "...kwwwwwwwwk...",
        "...kwwwwgwwwk...",
        "...kwwwggggwwk..",
        "...kwwgggggwwk..",
        "....kwwwwwwwk...",
        ".....kwwwwwk....",
        ".....krk.krk....",
        ".....krk.krk....",
      ],
    },
  },
  {
    id: "charran",
    name: "Charrán común",
    sci: "Sterna hirundo",
    family: "Laridae",
    rarity: 1,
    size: "31–35 cm",
    wingspan: "77–98 cm",
    desc: "Se cierne sobre el agua y se lanza en picado como una flecha para pescar. Cola larguísima ahorquillada, capirote negro y pico rojo en primavera.",
    fact: "Un charrán anillado en el Odiel fue visto cuatro meses después en Brasil: la migración de estas aves une continentes.",
    zones: ["agua"],
    time: { dawn: 1.3, day: 1.8, dusk: 1, night: 0.02 },
    skittish: 4,
    cry: 0,
    sprite: {
      pal: { k: K, w: "#f7f3e8", n: "#241830", g: "#9fb0bd", r: "#e04038", o: "#e8923c" },
      px: [
        "................",
        ".....nnnnk......",
        "....knnnnnk.....",
        "....krknnnk.....",
        "....kkknnwk.....",
        "......kwwwk.....",
        ".....kwwwwwk....",
        "....kwwwwwwwk...",
        "...kwwwwgwwwk...",
        "...kwwwgggwwwk..",
        "...kwwggggwwwk..",
        "....kwwwwwwkww..",
        ".....kwwwwwkkwk.",
        "......kwwwwk.kk.",
        ".....kok..kok...",
        ".....kok..kok...",
      ],
    },
  },
  {
    id: "charrancito",
    name: "Charrancito común",
    sci: "Sternula albifrons",
    family: "Laridae",
    rarity: 1,
    size: "21–25 cm",
    wingspan: "41–55 cm",
    desc: "El más pequeño de nuestros charranes, con la frente blanca y el pico amarillo de punta negra. Caza peces diminutos con vuelos cortos sobre la lámina de agua.",
    fact: "En la ría cría sobre la balsa sellada de los dragados: una de sus mayores colonias de España.",
    zones: ["agua"],
    time: { dawn: 1.2, day: 2, dusk: 1, night: 0.02 },
    skittish: 4,
    cry: 0,
    sprite: {
      pal: { k: K, w: "#f7f3e8", n: "#241830", y: "#ffd34e", o: "#e8923c" },
      px: [
        "................",
        "................",
        ".....nnnnk......",
        "....knnnnwk.....",
        "..nyykkwwwwk....",
        "....kkwwwwwk....",
        "......kwwwk.....",
        ".....kwwwwwk....",
        "....kwwwwwwwk...",
        "...kwwwgwwwwk...",
        "...kwwgggwwwk...",
        "....kwwwwwwwkw..",
        ".....kwwwwwkkw..",
        "......kwwwk.kk..",
        ".....kok..kok...",
        ".....kok..kok...",
      ],
    },
  },
  {
    id: "vuelvepiedras",
    name: "Vuelvepiedras común",
    sci: "Arenaria interpres",
    family: "Scolopacidae",
    rarity: 1,
    size: "22–24 cm",
    wingspan: "50–57 cm",
    desc: "Voltea piedras y algas con el pico buscando invertebrados; en vuelo parece llevar tirantes blancos sobre el dorso. Plumaje de mosaico rojo, negro y blanco.",
    fact: "Uno anillado en Suecia apareció en Portugal solo 11 días después: había volado 2.300 km a toda velocidad.",
    zones: ["fangal"],
    time: { dawn: 1.2, day: 1.1, dusk: 1, night: 0.05 },
    skittish: 3,
    cry: 0,
    sprite: {
      pal: { k: K, r: "#c8763c", n: "#241830", w: "#f7f3e8", o: "#e8923c" },
      px: [
        "................",
        "................",
        ".....rrrnk......",
        "....krrrrnk.....",
        "....kwkrrnk.....",
        "....kwkrrnnk....",
        ".....kwwnnnk....",
        ".....kwwnnnnk...",
        "....krwrrnnnk...",
        "...krrrrrnnnnk..",
        "...krwrrrwnnk...",
        "...krrwrrwwk....",
        "....krrrwwk.....",
        ".....kwwwwk.....",
        ".....kok.kok....",
        ".....kok.kok....",
      ],
    },
  },
  {
    id: "cormoran",
    name: "Cormorán grande",
    sci: "Phalacrocorax carbo",
    family: "Phalacrocoracidae",
    rarity: 0,
    size: "77–94 cm",
    wingspan: "121–160 cm",
    desc: "Bucea persiguiendo peces con todo el cuerpo, como una serpiente negra con reflejos verdes. Después se seca las alas abiertas en cruz sobre las rocas o las boyas.",
    zones: ["agua"],
    time: { dawn: 1.1, day: 1.1, dusk: 0.9, night: 0.05 },
    skittish: 3,
    cry: 1,
    sprite: {
      pal: { k: K, n: "#1a241f", g: "#3f5a48", y: "#e8c84c" },
      px: [
        "......kk........",
        ".....knnk.......",
        ".....knnk.......",
        "....kynnk.......",
        "....kygnk.......",
        ".....knnk.......",
        ".....knnk.......",
        ".....knnkk......",
        "....knggnnk.....",
        "...kngggggnnk...",
        "...knggggggnk...",
        "....kngggggnkk..",
        "....kngggggnnk..",
        ".....knnnnnnnk..",
        ".....kk.nnnnk...",
        "........kkkkk...",
      ],
    },
  },
  {
    id: "petirrojo",
    name: "Petirrojo europeo",
    sci: "Erithacus rubecula",
    family: "Muscicapidae",
    rarity: 0,
    size: "13–14 cm",
    wingspan: "20–22 cm",
    desc: "Su mancha naranja en cara, cuello y pecho lo hace inconfundible. De postura erguida y actitud confiada, visita parques y jardines en cuanto refresca.",
    fact: "Los petirrojos que nos visitan en invierno llegan de Escandinavia: algunos anillados allí se han recuperado en Huelva.",
    zones: ["matorral"],
    time: { dawn: 1.4, day: 1, dusk: 1.3, night: 0.3 },
    skittish: 2,
    cry: 2,
    sprite: {
      pal: { k: K, b: "#8a6a44", o: "#e8562e", w: "#f7f3e8", R: "#6b4a36" },
      px: [
        "..........R.....",
        ".....kk...R.....",
        "....kbbk..R.....",
        "...kkbobk.R.....",
        "...kkoobbk......",
        "....koobbbk.....",
        "....koobbbbkk...",
        "....koowbbbbk...",
        "....kowwbbbbk...",
        "....kowwbbbbk...",
        ".....kowwbbk....",
        ".....kkwbbk.....",
        "......kbbkk.....",
        ".......kkRk.....",
        "........RR......",
        "........RR......",
      ],
    },
  },
  {
    id: "mirlo",
    name: "Mirlo común",
    sci: "Turdus merula",
    family: "Turdidae",
    rarity: 0,
    size: "24–27 cm",
    wingspan: "34–38 cm",
    desc: "El macho es negro brillante, de mediano tamaño y larga cola, con pico y anillo ocular anaranjados. Común en zonas forestales y jardines urbanos: de las primeras aves en cantar, incluso antes del amanecer.",
    fact: "Al sentirse amenazado emite un característico sonido de alerta mientras vuela buscando refugio entre la espesura.",
    zones: ["matorral"],
    time: { dawn: 1.6, day: 0.9, dusk: 1.4, night: 0.4 },
    skittish: 3,
    cry: 2,
    sprite: {
      pal: { k: K, n: "#23242e", y: "#f0a838", R: "#6b4a36" },
      px: [
        "..........R.....",
        ".....kk...R.....",
        "....knnk..R.....",
        "...kknnnk.R.....",
        "...kyyknnyk.....",
        "....kynnnk......",
        "....knnnnnkk....",
        "...knnnnnnnnk...",
        "...knnnnnnnnk...",
        "...knnnnnnnnnk..",
        "....knnnnnnnnk..",
        "......knnnnnkk..",
        "......kk.kk.R...",
        "........RR......",
        "........RR......",
        "................",
      ],
    },
  },
  {
    id: "jilguero",
    name: "Jilguero europeo",
    sci: "Carduelis carduelis",
    family: "Fringillidae",
    rarity: 1,
    size: "12–14 cm",
    wingspan: "21–25 cm",
    desc: "Pequeña ave de plumaje muy vistoso: el inconfundible «madroño» rojo en la cara corona un diseño de negro, blanco y oro, con la franja alar amarilla bien visible. En invierno forma bandadas que se posan en los cardos a comer semillas.",
    fact: "En Huelva lo llaman «colorín». La guía advierte que es una de las aves que más se captura ilegalmente para enjaularla por su precioso canto.",
    zones: ["matorral"],
    time: { dawn: 1.3, day: 1.5, dusk: 1, night: 0.05 },
    skittish: 3,
    cry: 2,
    sprite: {
      pal: { k: K, r: "#e0382e", n: "#241830", w: "#f7f3e8", b: "#8a6a44", y: "#ffd34e", R: "#6b4a36" },
      px: [
        "..........R.....",
        ".....nnk..R.....",
        "....knnnk.R.....",
        "...krrenwk......",
        "...krrwnbk......",
        "....krrwbbk.....",
        "....kwwybbbkk...",
        "....kwwyybbbk...",
        "....kwybbbbbk...",
        "....kwwbbbbbk...",
        ".....kwwbbbk....",
        ".....kkwbbk.....",
        "......kk.kkR....",
        "........RR......",
        "........RR......",
        "................",
      ],
    },
  },
  {
    id: "aguilucho",
    name: "Aguilucho lagunero",
    sci: "Circus aeruginosus",
    family: "Accipitridae",
    rarity: 2,
    size: "48–60 cm",
    wingspan: "110–140 cm",
    desc: "El pirata de las marismas: patrulla los carrizales a ras de caña, con las alas en uve abierta, buscando nidos y pollas de agua. El macho es gris ceniza con alas de tres colores y obispillo blanco.",
    fact: "La hembra es parda y bastante mayor que el macho: juntos forman una de las parejas más llamativas del carrizal.",
    zones: ["carrizal", "matorral"],
    time: { dawn: 1.8, day: 0.9, dusk: 1.8, night: 0.05 },
    skittish: 5,
    cry: 3,
    sprite: {
      pal: { k: K, g: "#9aa7b5", n: "#2a3140", w: "#f7f3e8" },
      px: [
        "kk............kk",
        "knnk........knnk",
        "knnngk....kgggnk",
        ".kggggk..kggggk.",
        "..kggggkkggggk..",
        "...kggggggggk...",
        "....kgggggggk...",
        ".....kggwwggk...",
        ".....kgwwwwwk...",
        "......kgwwwgk...",
        "......kggwwwk...",
        ".......kgggk....",
        ".......kgggk....",
        "........kkkk....",
        "................",
        "................",
      ],
    },
  },
  {
    id: "aguila-pescadora",
    name: "Águila pescadora",
    sci: "Pandion haliaetus",
    family: "Pandionidae",
    rarity: 3,
    size: "52–60 cm",
    wingspan: "150–180 cm",
    desc: "Caza peces lanzándose al agua con las garras por delante. En el Odiel, una de sus últimas fortalezas europeas, se la ve pescar en los caños al amanecer.",
    fact: "Está catalogada como vulnerable. La guía del puerto la destaca como una de las joyas que crían en el paraje.",
    zones: ["agua"],
    time: { dawn: 3, day: 0.8, dusk: 1.5, night: 0.02 },
    skittish: 5,
    cry: 3,
    sprite: {
      pal: { k: K, n: "#3a2c22", w: "#f7f3e8", y: "#e8b64c" },
      px: [
        ".....kkkk.......",
        "....kwwwwk......",
        "....kwkywk......",
        "....kwnnwwk.....",
        "....ykwnnwk.....",
        ".....kwwwwk.....",
        ".....kwwkkk.....",
        "....kwwnnnnkk...",
        "...kwwnnnnnnk...",
        "...kwnnnnnnnk...",
        "...kwnnnnnnnk...",
        "....kwwnnnnk....",
        "....kwwwwwwk....",
        ".....kwwwwk.....",
        ".....kyk.kyk....",
        ".....kkk.kkk....",
      ],
    },
  },
];

// ─── Sprites de Anna, la protagonista (abajo, arriba, lado; 2 fotogramas) ───
const ANNA_PAL: Record<string, string> = {
  k: K,
  b: "#c8a24a", // sombrero de paja
  h: "#d95f3b", // pelo pelirrojo
  s: "#f2c9a0", // piel
  t: "#2f8f83", // camisa
  p: "#5b4632", // pantalón
};

const annaDown0 = [
  "................",
  ".....bbbbbb.....",
  "....kbbbbbbk....",
  "....khsssshk....",
  "....khskskhk....",
  ".....kssssk.....",
  "....kttttttk....",
  "...ksttkkttsk...",
  "...ksttkkttsk...",
  "....kppppppk....",
  "....kppkkppk....",
  "....kppk.kppk...",
  "....kppk.kppk...",
  "....kkkk.kkkk...",
  "................",
  "................",
];
const annaDown1 = [
  "................",
  ".....bbbbbb.....",
  "....kbbbbbbk....",
  "....khsssshk....",
  "....khskskhk....",
  ".....kssssk.....",
  "....kttttttk....",
  "...ksttkkttsk...",
  "...ksttkkttsk...",
  "....kppppppk....",
  "....kppk..kppk..",
  "....kppk..kppk..",
  "....kppk..kppk..",
  "....kkkk..kkkk..",
  "................",
  "................",
];
const annaUp0 = [
  "................",
  ".....bbbbbb.....",
  "....kbbbbbbk....",
  "....khhhhhhk....",
  "....khhhhhhk....",
  "....khhhhhhk....",
  "....khhhhhhk....",
  "...ksttkkttsk...",
  "...ksttkkttsk...",
  "....kppppppk....",
  "....kppkkppk....",
  "....kppk.kppk...",
  "....kppk.kppk...",
  "....kkkk.kkkk...",
  "................",
  "................",
];
const annaSide0 = [
  "................",
  "....bbbbbb......",
  "...kbbbbbbk.....",
  "...khhssssk.....",
  "...khkskssk.....",
  "....kkssssk.....",
  "....ktttttk.....",
  "...kstttttk.....",
  "...kstttttk.....",
  "....kppppk......",
  "....kppppk......",
  "....kpppk.......",
  "....kppk........",
  "....kkkk........",
  "................",
  "................",
];
const annaSide1 = [
  "................",
  "....bbbbbb......",
  "...kbbbbbbk.....",
  "...khhssssk.....",
  "...khkskssk.....",
  "....kkssssk.....",
  "....ktttttk.....",
  "...kstttttk.....",
  "...kstttttk.....",
  "....kppppk......",
  "....kppppk......",
  "....kppk........",
  "....kpppk.......",
  "....kkkk........",
  "................",
  "................",
];

export const ANNA: Record<string, Sprite[]> = {
  down: [
    { pal: ANNA_PAL, px: annaDown0 },
    { pal: ANNA_PAL, px: annaDown1 },
  ],
  up: [
    { pal: ANNA_PAL, px: annaUp0 },
    { pal: ANNA_PAL, px: annaUp0 },
  ],
  side: [
    { pal: ANNA_PAL, px: annaSide0 },
    { pal: ANNA_PAL, px: annaSide1 },
  ],
};
